# Generated by Django 3.2.5 on 2021-07-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicationNotasAlunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('periodoIngresso', models.CharField(max_length=10, verbose_name='Período Ingresso')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Nota')),
                ('situação', models.IntegerField(verbose_name='Situação')),
            ],
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='estoque',
            new_name='situação',
        ),
    ]
