# Generated by Django 3.2.5 on 2021-07-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicationNotasAlunos', '0002_auto_20210730_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='situação',
            field=models.CharField(max_length=50, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='alunoinfo',
            name='situação',
            field=models.CharField(max_length=50, verbose_name='Situação'),
        ),
    ]
