# Generated by Django 3.2.5 on 2021-07-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicationNotasAlunos', '0003_auto_20210730_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='situação',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='alunoinfo',
            old_name='situação',
            new_name='situaacao',
        ),
    ]
